modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
description = "${description}"
logoFile = "assets/${id}/icon.png"
authors = ["lupiiin_", "lowercasebtw", "luavixen <lua@foxgirl.dev> (https://foxgirl.dev/)"]
displayURL = "${modrinth}"

[[mixins]]
config = "${id}.mixins.json"

[[dependencies.${id}]]
modId = "neoforge"
mandatory = true
versionRange = "[21.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"
